{{#with lambda}}
{{template.name}}Trigger:
  Type: "AWS::Events::Rule"
  Properties:
    Description: Stardust Simulation Trigger
    ScheduleExpression: {{function.rate}}
    State: ENABLED
    Targets:
      - Id: {{template.name}}
        Arn: {{function.arn}}
        Input: {{function.input}}

{{template.name}}TriggerRole:
  DependsOn:
    - {{template.name}}Trigger
  Type: "AWS::Lambda::Permission"
  Properties:
    Action: "lambda:InvokeFunction"
    FunctionName: {{function.arn}}
    Principal: events.amazonaws.com
    SourceArn:
      "Fn::GetAtt": [{{template.name}}Trigger, "Arn"]
{{/with}}
