{{template.name}}:
  Type: "AWS::Lambda::Function"
  Properties:
    Description: "Stardust Lambda for {{@root.name}} {{@root.env}}"
    FunctionName: {{function.name}}

    Handler: "stardust/lib/stardust.handler"
    Role:
      "Fn::GetAtt" : ["{{@root.roleName}}", "Arn"]
    Runtime: {{@root.environment.runtime}}
    MemorySize: {{@root.environment.memorySize}}
    Timeout: {{@root.environment.timeout}}
    Environment:
      Variables:
      {{#each @root.environmentVariables}}
        {{@key}}: {{this}}
      {{/each}}
    Code:
      S3Bucket: {{template.bucket}}
      S3Key: "package.zip"
    {{#if @root.aws.vpc}}
    VpcConfig:
      SecurityGroupIds:
        "Fn::Split" : [ ",", {"Ref": SecurityGroups} ]
      SubnetIds:
        "Fn::Split" : [ ",", {"Ref": Subnets} ]
    {{/if}}  
