{{#with lambda}}
{{template.name}}:
  Type: "AWS::Lambda::Function"
  Properties:
    Description: "Stardust Simulation for {{@root.name}} {{@root.env}}"
    FunctionName: {{function.name}}

    Handler: "stardust/lib/stardust.tests"
    Role:
      "Fn::GetAtt" : ["{{@root.roleName}}", "Arn"]
    Runtime: {{@root.aws.runtime}}
    MemorySize: 256
    {{#if @root.aws.vpc}}
    VpcConfig:
      SecurityGroupIds:
        "Fn::Split" : [ ",", {"Ref": SecurityGroups} ]
      SubnetIds:
        "Fn::Split" : [ ",", {"Ref": Subnets} ]
    {{/if}}
    Environment:
      Variables:
      {{#eachProperty @root.environmentVariables}}
        {{key}}: {{value}}
      {{/eachProperty}}
  {{#if timeout}}
    Timeout: {{timeout}}
  {{else}}
    Timeout: 300
  {{/if}}
    Code:
      S3Bucket: {{template.bucket}}
      S3Key: "package.zip"
{{/with}}
