$schema: http://json-schema.org/draft-04/schema#
title: Stardust Configuration Description

type: object
required:
  - source
  - name
  - projectID
properties:
  source:
    type: string

  name:
    description: >
      Name for your project.  This will appear in all the
      environment names when you deploy CloudFormation stacks.
    type: string

  description:
    description: Optional description for your project's purpose.
    type: string

  projectID:
    description: >
      A unique ID tied to your project across Cloud resources.  When a globally
      unique name is required, such as the S3 bucket used to orchestrate your
      deployment, this ID is part of the name.  This is generated for you
      when you use 'sky init', or you may provide your own.
    type: string

  tags:
    description: >
      Optional tags attached to your deployed resources when possible to make
      it easier to track and monitor. These are applied to all environments.
    type: array
    minItems: 1
    uniqueItems: true
    items:
      type: object
      additionalProperties: false
      required: [ Key, Value ]
      properties:
        Key:
          description: >
            Name of tag. This is an arbitrary string you provide to track
            resource groupings of interest.
          type: string
        Value:
          description: >
            The value that goes with the matching tag type. This is an
            aribitrary string you provide to track resource groupings of
            interest.
          type: string
