AWSTemplateFormatVersion: "2010-09-09"
Description: "{{env}} {{name}} - Stardust Simulations"
Resources:
  StardustCore:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        - Key: Substack Type
          Value: Core
        {{#each tags}}
        - Key: {{Key}}
          Value: {{Value}}
        {{/each}}
      TemplateURL: "https://{{environmentVariables.starBucket}}.s3.amazonaws.com/templates/core/index.yaml"

  {{#if needsMixinResources}}
  StarMixins:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        - Key: Substack Type
          Value: Mixins Top Level
        {{#each tags}}
        - Key: {{Key}}
          Value: {{Value}}
        {{/each}}
      TemplateURL: "https://{{environmentVariables.starBucket}}.s3.amazonaws.com/templates/mixins/index.yaml"
  {{/if}}
