AWSTemplateFormatVersion: "2010-09-09"
Description: Stardust Core Resources
Resources:
  LambdaFunctions:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Tags:
        - Key: Substack Type
          Value: Core Lambda Functions
        {{#each tags}}
        - Key: {{Key}}
          Value: {{Value}}
        {{/each}}
      TemplateURL: "https://{{environmentVariables.starBucket}}.s3.amazonaws.com/templates/core/lambda-functions.yaml"
