AWSTemplateFormatVersion: "2010-09-09"
Description: Panda Sky Core Resources - Lambda Functions
{{#if aws.vpc}}
Parameters:
  SecurityGroups:
    Type: String
    Description: comma delimited list of security groups for the core stack VPC
  Subnets:
    Type: String
    Description: comma delimited list of subnet IDs for the core stack VPC
{{/if}}
Resources:
  # IAM (Identity and Access Management), granting functions acccess to other stack resources.
  {{> iamrole}}

  # Define all Lambdas for methods on all non-root resources
  {{#with environment}}
  {{#each simulations}}
  {{> lambda }}
  {{/each}}
  {{#each functionals}}
  {{> lambda }}
  {{/each}}
  {{/with}}

Outputs:
  isDone:
    Value: "true"
