AWSTemplateFormatVersion: "2010-09-09"
Description: Panda Sky Core Resources - Lambda Functions
Resources:
  # IAM (Identity and Access Management), granting functions acccess to other stack resources.
  {{> iamrole}}

  # Define all Lambdas for methods on all non-root resources
  {{#with environment}}
  {{#each simulations}}
  {{> lambda }}
  {{/each}}
  {{#each functionals}}
  {{> lambda }}
  {{/each}}
  {{/with}}
